apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  labels:
    io.kompose.service: api-basic-jwt
  name: api-basic-jwt
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: api-basic-jwt
status:
  loadBalancer: {}
