apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: "kompose convert"
    kompose.version: "1.31.2 (HEAD)"
  labels:
    io.kompose.service: api-basic-jwt
  name: api-basic-jwt
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: api-basic-jwt
  template:
    metadata:
      annotations:
        kompose.cmd: "kompose convert"
        kompose.version: "1.31.2 (HEAD)"
      labels:
        io.kompose.network/api-basic-jwt-default: "true"
        io.kompose.service: api-basic-jwt
    spec:
      containers:
        - image: d4rkghost47/api-basic-jwt:v1
          name: api-basic-jwt
          ports:
            - containerPort: 8081
              hostPort: 8081
              protocol: TCP

          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              memory: "256Mi"
              cpu: "200m"
      restartPolicy: Always

